application: fb-img
version: 1
runtime: python
api_version: 1

handlers:
- url: /imgup(|/(.*))
  script: imgup/app.py
  
- url: /united/(.*)
  script: united/app.py

- url: /kitchen(|/(.*))
  script: virmanikitchen/app.py
 
- url: /portal(|.csv|/(.*))
  script: portal/app.py

- url: /yn/foo
  script: hnstats/app.py
  
- url: /yn(/process|/search|/job)
  script: hnstats/app.py
  login: admin
  
- url: /yn
  script: hnstats/app.py
  
  
  
- url: /urlrank
  script: urlrank/app.py
  
- url: /rank(|/(u|s))
  script: rank/app.py
  
  
  
- url: /vbb/admin/bulk/(upload|download)
  script: vbb/admin-bulk.py

- url: /vbb/admin/demos
  script: vbb/admin.py

- url: /vbb/admin(|/sections(|/(.*)))
  script: vbb/admin.py

- url: /vbb(|/.*(|/.*))
  script: vbb/app.py
  
  

- url: /s3test
  script: s3test/s3test.py

- url: /newsy(|/(.*))
  script: newsy/newsy.py

- url: /
  script: michaelshafrir/routes.py

- url: /static
  static_dir: static
  
- url: /sitemap.xml
  static_files: static/site/sitemap.xml
  upload: static/site/sitemap.xml
   
- url: /robots.txt
  static_files: static/site/robots.txt
  upload: static/site/robots.txt
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico